### ISSUE TITLE
the link for iso is dead

### ISSUE THREAD

**Issue by philmb3487** [pendor/gentoo-zfs-install#5]
http://dl.dropbox.com/u/34890805/install-amd64-minimal-10.0.zfs.iso
is dead. 404

**Comment by pendor** [comment]
It's actually not necessary any more. You can still more or less follow those instructions to get a root ZFS, but Gentoo started including the ZFS modules in their standard live cd images. No need for a special ISO anymore. 

Best regards,
Zac Bedell

**Comment by philmb3487** [comment]
That's weird, I can't find ZFS on the ISO I just downloaded. 20160225 livecd
